name: Java Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: |
        cd /home/runner/work/SQEProject/SQEProject/JtProject
        mvn -B clean verify

    - name: Run Tests
      run: |
        cd /home/runner/work/SQEProject/SQEProject/JtProject
        mvn test
